environment:
  density: High
  noise_level: Moderate
  setting: Urban downtown
location:
  city: NYC
  country: USA
  region: Northeast
simulation_parameters:
  detail_level: high
  initial_time: auto
  time_flow_rate: 1.0
starting_location: unknown
